<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MacBook-Pro" ignored="0" name="Test" tests="7" failures="2" timestamp="07 Jan 2019 11:24:47 GMT" time="0.054" errors="0">
  <testcase name="Test1" time="0.012" classname="com.app.tests.FailureTestCase"/>
  <testcase name="Test2" time="0.002" classname="com.app.tests.FailureTestCase">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="com.app.tests.FailureTestCase">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.002" classname="com.app.tests.FailureTestCase">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:92)
at org.junit.Assert.assertTrue(Assert.java:43)
at org.junit.Assert.assertTrue(Assert.java:54)
at com.app.tests.FailureTestCase.Test2(FailureTestCase.java:16)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase name="Test3" time="0.001" classname="com.app.tests.FailureTestCase">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase name="Test3" time="0.001" classname="com.app.tests.FailureTestCase">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase name="Test3" time="0.001" classname="com.app.tests.FailureTestCase">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:92)
at org.junit.Assert.assertTrue(Assert.java:43)
at org.junit.Assert.assertTrue(Assert.java:54)
at com.app.tests.FailureTestCase.Test3(FailureTestCase.java:21)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Test3 -->
</testsuite> <!-- Test -->
